export const config = { runtime: 'edge' };
export default async function handler(req) {
  const chunks = [
    '<!DOCTYPE html><html lang="zh"><head><meta charset="UTF-8">',
    '<meta name="viewport" content="width=device-width,initial-scale=1.0">',
    '',
    '<title>Bulk 2FA Authenticator | 批量2FA/双重验证码生成工具</title>',
    '<meta name="description" content="专业级批量 2FA 验证工具。双重验证码/ 2fa验证器获取（2FA）工具（类似于谷歌身份验证器的网页版），支持多账号导入，单列清晰大字设计，纯本地安全计算。">',
    '<link rel="icon" href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 100 100%22><text y=%22.9em%22 font-size=%2290%22>🛡️</text></svg>">',
    '<script src="https://cdn.jsdelivr.net/npm/otpauth@9.1.4/dist/otpauth.umd.min.js"></script>',
    '<style>:root{--primary:#4361ee;--bg-gradient:linear-gradient(135deg, #667eea 0%, #764ba2 100%)}',
    'body{font-family:"Inter",-apple-system,sans-serif;background:var(--bg-gradient);margin:0;padding:20px 15px;min-height:100vh;display:flex;flex-direction:column;align-items:center;color:#2d3436;box-sizing:border-box}',
    '.container{background:rgba(255,255,255,0.92);backdrop-filter:blur(15px);padding:2rem;border-radius:28px;box-shadow:0 20px 40px rgba(0,0,0,0.2);width:100%;max-width:550px;text-align:center}',
    'h1{font-size:1.1rem;color:#636e72;text-transform:uppercase;letter-spacing:2px;margin-bottom:1.5rem}',
    '.example-box{background:rgba(67,97,238,0.08);border-left:4px solid var(--primary);padding:12px;text-align:left;border-radius:8px;margin-bottom:15px;font-size:0.85rem;color:#4b5563;line-height:1.6}',
    '.example-box code{background:#fff;padding:2px 4px;border-radius:4px;color:var(--primary);font-family:monospace;font-weight:bold}',
    'textarea{width:100%;height:140px;padding:15px;border:2px solid #dfe6e9;border-radius:18px;box-sizing:border-box;background:rgba(255,255,255,0.5);font-size:1rem;outline:none;transition:all 0.3s;font-family:monospace}',
    'textarea:focus{border-color:var(--primary);background:#fff}button{background:var(--primary);color:#fff;border:none;padding:14px 40px;border-radius:14px;font-size:1.1rem;font-weight:600;margin-top:15px;cursor:pointer;transition:all 0.2s;width:100%}',
    'button:hover{transform:translateY(-2px);box-shadow:0 8px 20px rgba(67,97,238,0.3)}',
    '#list{margin-top:20px;width:100%}.card{background:white;padding:18px 22px;border-radius:20px;box-shadow:0 8px 15px rgba(0,0,0,0.04);border:1px solid rgba(0,0,0,0.05);margin-bottom:15px;display:flex;flex-direction:column;align-items:center;transition:all 0.3s;position:relative}',
    '.card:hover{transform:translateY(-3px);box-shadow:0 12px 25px rgba(0,0,0,0.08);border-color:var(--primary)}',
    '.acc{font-size:1.15rem;font-weight:700;color:#2d3436;margin-bottom:8px;word-break:break-all;width:100%;text-align:center}',
    '.otp-val{font-size:2.6rem;font-weight:800;color:var(--primary);letter-spacing:4px;cursor:pointer;font-family:"Roboto Mono",monospace;margin:5px 0}',
    '.timer-container{width:100%;height:6px;background:#f1f2f6;border-radius:10px;margin-top:15px;overflow:hidden}',
    '.timer-bar{height:100%;background:var(--primary);width:100%;transition:width 1s linear}',
    '.back-link{margin-top:30px;color:rgba(255,255,255,0.8);text-decoration:none;font-size:0.9rem;transition:color 0.2s}.back-link:hover{color:#fff}',
    '.toast{position:fixed;bottom:40px;left:50%;transform:translateX(-50%);background:rgba(0,0,0,0.85);color:#fff;padding:12px 30px;border-radius:30px;display:none;z-index:100;font-weight:600}</style></head>',
    '<body><div class="container"><h1 id="t">🛡️ Bulk Authenticator</h1>',
    '<div id="input-area"><div class="example-box" id="eb"></div><textarea id="i"></textarea><button onclick="load()" id="b"></button></div>',
    '<div id="list"></div></div><a href="/" class="back-link" id="bk"></a><div id="ts" class="toast"></div>',
    '<script>',
    'const lang=navigator.language.startsWith("zh")?"zh":"en";',
    'const i18n={zh:{t:"🛡️ 批量验证器",b:"立即生成验证码",bk:"← 返回单账号模式",s:"验证码已复制",p:"每行一个，例如：\\nmyname@gmail.com JBSWY3DPEHPK3PXP",eb:"<strong>输入说明：</strong><br>请在下方输入您的账号信息，格式为：<code>账号 密钥</code>（中间用空格或制表符分隔），每行一组。支持批量从 Excel 直接粘贴。"},en:{t:"🛡️ Bulk Authenticator",b:"Generate Codes",bk:"← Single Mode",s:"Copied",eb:"<strong>Instructions:</strong><br>Enter your data as <code>Account Secret</code> per line. You can copy and paste directly from Excel or TXT files.",p:"Example:\\nuser@mail.com JBSWY3DPEHPK3PXP"}};',
    'const D=id=>document.getElementById(id);',
    'D("t").innerHTML=i18n[lang].t;D("b").innerText=i18n[lang].b;D("bk").innerText=i18n[lang].bk;D("i").placeholder=i18n[lang].p;D("eb").innerHTML=i18n[lang].eb;',
    'let acts=[];',
    'function load(){const lines=D("i").value.trim().split("\\n");acts=[];for(let l of lines){let p=l.trim().split(/\\s+|\\t/).filter(x=>x);if(p.length<2)continue;try{',
    'const n=p[0];const s=p[p.length-1].toUpperCase().replace(/\\s+/g,"");',
    'const totp=new OTPAuth.TOTP({secret:OTPAuth.Secret.fromBase32(s)});',
    'acts.push({n:n,t:totp})}catch(e){}}if(acts.length>0){upd();D("input-area").style.display="none"}}',
    'function upd(){const l=D("list");const r=30-(Math.floor(Date.now()/1000)%30);l.innerHTML="";for(let a of acts){',
    'const c=a.t.generate();const div=document.createElement("div");div.className="card";',
    'div.innerHTML=`<div class="acc" title="\${a.n}">\${a.n}</div><div class="otp-val" onclick="cp(\'\${c}\')">\${c}</div><div class="timer-container"><div class="timer-bar" style="width:\${(r/30)*100}%"></div></div>`;',
    'l.appendChild(div)}if(r===30)setTimeout(upd,500)}',
    'function cp(t){navigator.clipboard.writeText(t).then(()=>{const s=D("ts");s.innerText=i18n[lang].s;s.style.display="block";setTimeout(()=>s.style.display="none",2000)})}',
    'setInterval(()=>{if(acts.length>0)upd()},1000);',
    '</script></body></html>'
  ];
  return new Response(chunks.join(''), { headers: { "Content-Type": "text/html;charset=UTF-8" } });
}
