export const config = { runtime: 'edge' };
export default async function handler(req) {
  const chunks = [
    '<!DOCTYPE html><html lang="zh"><head><meta charset="UTF-8">',
    '<meta name="viewport" content="width=device-width,initial-scale=1.0">',
    '<title>Bulk 2FA | 在线批量2FA验证码生成器</title>',
    '<meta name="description" content="安全、私密的批量 2FA 验证器。支持 20+ 账号一屏显示，纯本地计算，极致视觉体验。">',
    '<link rel="icon" href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 100 100%22><text y=%22.9em%22 font-size=%2290%22>🛡️</text></svg>">',
    '<script src="https://cdn.jsdelivr.net/npm/otpauth@9.1.4/dist/otpauth.umd.min.js"></script>',
    '<style>:root{--primary:#4361ee;--bg-gradient:linear-gradient(135deg, #667eea 0%, #764ba2 100%)}',
    'body{font-family:"Inter",system-ui,-apple-system,sans-serif;background:var(--bg-gradient);margin:0;padding:20px;min-height:100vh;display:flex;justify-content:center;align-items:flex-start;color:#2d3436;box-sizing:border-box}',
    '.container{background:rgba(255,255,255,0.9);backdrop-filter:blur(15px);padding:2rem;border-radius:24px;box-shadow:0 20px 40px rgba(0,0,0,0.2);width:100%;max-width:1100px;text-align:center}',
    'h1{font-size:1.1rem;color:#636e72;text-transform:uppercase;letter-spacing:2px;margin-bottom:1.5rem}',
    '.input-section{margin-bottom:2rem}textarea{width:100%;height:100px;padding:14px;border:2px solid #dfe6e9;border-radius:16px;box-sizing:border-box;background:rgba(255,255,255,0.5);font-size:0.9rem;outline:none;transition:all 0.3s}',
    'textarea:focus{border-color:var(--primary);background:#fff}button{background:var(--primary);color:#fff;border:none;padding:12px 30px;border-radius:12px;font-size:1rem;font-weight:600;margin-top:15px;cursor:pointer;transition:all 0.2s}',
    'button:hover{transform:translateY(-2px);box-shadow:0 5px 15px rgba(67,97,238,0.3)}',
    '#grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(240px,1fr));gap:20px;margin-top:20px}',
    '.card{background:white;padding:1.5rem;border-radius:20px;box-shadow:0 8px 20px rgba(0,0,0,0.05);border:1px solid rgba(0,0,0,0.03);position:relative;transition:all 0.3s;display:flex;flex-direction:column;align-items:center}',
    '.card:hover{transform:translateY(-5px);box-shadow:0 12px 30px rgba(0,0,0,0.1)}',
    '.acc-label{font-size:0.75rem;color:#b2bec3;margin-bottom:8px;word-break:break-all;max-width:100%}',
    '.otp-val{font-size:1.8rem;font-weight:800;color:var(--primary);letter-spacing:2px;cursor:pointer;margin:5px 0}',
    '.timer-wrap{width:100%;height:6px;background:#dfe6e9;border-radius:3px;margin-top:12px;overflow:hidden}',
    '.timer-bar{height:100%;background:var(--primary);width:100%;transition:width 1s linear}',
    '.back-link{display:block;margin-top:30px;color:rgba(255,255,255,0.8);text-decoration:none;font-size:0.85rem}',
    '.toast{position:fixed;bottom:30px;left:50%;transform:translateX(-50%);background:rgba(0,0,0,0.85);color:#fff;padding:10px 24px;border-radius:30px;display:none;z-index:100}</style></head>',
    '<body><div style="width:100%;max-width:1100px"><div class="container"><h1 id="t">🛡️ Bulk Authenticator</h1>',
    '<div class="input-section"><textarea id="i"></textarea><br><button onclick="load()" id="b">Generate</button></div>',
    '<div id="grid"></div></div><a href="/" class="back-link" id="bk"></a></div><div id="ts" class="toast"></div>',
    '<script>',
    'const lang=navigator.language.startsWith("zh")?"zh":"en";',
    'const i18n={zh:{t:"🛡️ 批量验证器",b:"立即生成",bk:"← 返回单账号模式",s:"已复制",p:"在此粘贴清单，例如：\\nuser@mail.com SECRET_KEY"},en:{t:"🛡️ Bulk Authenticator",b:"Generate Codes",bk:"← Single OTP Mode",s:"Copied",p:"Paste list here: email secret..."}};',
    'const D=id=>document.getElementById(id);',
    'D("t").innerText=i18n[lang].t;D("b").innerText=i18n[lang].b;D("bk").innerText=i18n[lang].bk;D("i").placeholder=i18n[lang].p;',
    'let acts=[];',
    'function load(){const lines=D("i").value.trim().split("\\n");acts=[];for(let l of lines){let p=l.trim().split(/\\s+|\\t/).filter(x=>x);if(p.length<2)continue;try{',
    'const n=p[0];const s=p[p.length-1].toUpperCase().replace(/\\s+/g,"");',
    'const totp=new OTPAuth.TOTP({secret:OTPAuth.Secret.fromBase32(s)});',
    'acts.push({n:n,t:totp})}catch(e){}}if(acts.length>0){upd();D("i").style.display="none";D("b").style.display="none"}}',
    'function upd(){const g=D("grid");const r=30-(Math.floor(Date.now()/1000)%30);g.innerHTML="";for(let a of acts){',
    'const c=a.t.generate();const div=document.createElement("div");div.className="card";',
    'div.innerHTML=`<div class="acc-label">\${a.n}</div><div class="otp-val" onclick="cp(\'\${c}\')">\${c}</div><div style="font-size:0.7rem;margin-top:5px;color:#e74c3c">Expiring in \${r}s</div><div class="timer-wrap"><div class="timer-bar" style="width:\${(r/30)*100}%"></div></div>`;',
    'g.appendChild(div)}if(r===30)setTimeout(upd,500)}',
    'function cp(t){navigator.clipboard.writeText(t).then(()=>{const s=D("ts");s.innerText=i18n[lang].s+": "+t;s.style.display="block";setTimeout(()=>s.style.display="none",2000)})}',
    'setInterval(()=>{if(acts.length>0)upd()},1000);',
    '</script></body></html>'
  ];
  return new Response(chunks.join(''), { headers: { "Content-Type": "text/html;charset=UTF-8" } });
}
