export const config = { runtime: 'edge' };
export default async function handler(req) {
  const chunks = [
    '<!DOCTYPE html><html lang="zh"><head><meta charset="UTF-8">',
    '<meta name="viewport" content="width=device-width,initial-scale=1.0">',
    '',
    '<title>Bulk 2FA | 高效批量在线2FA身份验证器</title>',
    '<meta name="description" content="专业级批量 2FA 验证码生成工具。双列紧凑布局，支持多账号一屏管理，安全私密，纯本地计算。">',
    '<meta name="keywords" content="批量2FA, 验证码生成器, OTP批量, Google Authenticator 网页版, 账号管理">',
    '<link rel="icon" href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 100 100%22><text y=%22.9em%22 font-size=%2290%22>🛡️</text></svg>">',
    '<script src="https://cdn.jsdelivr.net/npm/otpauth@9.1.4/dist/otpauth.umd.min.js"></script>',
    '<style>:root{--primary:#4361ee;--bg-gradient:linear-gradient(135deg, #667eea 0%, #764ba2 100%)}',
    'body{font-family:"Inter",system-ui,-apple-system,sans-serif;background:var(--bg-gradient);margin:0;padding:15px;min-height:100vh;display:flex;justify-content:center;color:#2d3436;box-sizing:border-box}',
    '.container{background:rgba(255,255,255,0.9);backdrop-filter:blur(15px);padding:1.5rem;border-radius:24px;box-shadow:0 20px 40px rgba(0,0,0,0.2);width:100%;max-width:800px;text-align:center}',
    'h1{font-size:1rem;color:#636e72;text-transform:uppercase;letter-spacing:2px;margin-bottom:1rem}',
    'textarea{width:100%;height:100px;padding:12px;border:2px solid #dfe6e9;border-radius:16px;box-sizing:border-box;background:rgba(255,255,255,0.5);font-size:0.85rem;outline:none;transition:all 0.3s}',
    'textarea:focus{border-color:var(--primary);background:#fff}button{background:var(--primary);color:#fff;border:none;padding:10px 25px;border-radius:10px;font-size:0.9rem;font-weight:600;margin-top:10px;cursor:pointer;transition:all 0.2s}',
    'button:hover{transform:translateY(-1px);box-shadow:0 5px 15px rgba(67,97,238,0.3)}',
    '#grid{display:grid;grid-template-columns:repeat(2, 1fr);gap:10px;margin-top:15px;text-align:left}',
    '.card{background:white;padding:10px 15px;border-radius:14px;border:1px solid rgba(0,0,0,0.05);display:flex;align-items:center;justify-content:space-between;transition:all 0.2s}',
    '.card:hover{border-color:var(--primary);box-shadow:0 4px 12px rgba(0,0,0,0.05)}',
    '.info{overflow:hidden;margin-right:10px}.acc{font-size:0.75rem;color:#95a5a6;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;max-width:180px}',
    '.otp-val{font-size:1.4rem;font-weight:800;color:var(--primary);letter-spacing:1px;cursor:pointer;font-family:monospace}',
    '.timer-mini{font-size:0.65rem;color:#e74c3c;font-weight:bold;margin-top:2px}',
    '.back-link{display:block;margin-top:20px;color:rgba(255,255,255,0.7);text-decoration:none;font-size:0.75rem}',
    '.toast{position:fixed;bottom:30px;left:50%;transform:translateX(-50%);background:rgba(0,0,0,0.85);color:#fff;padding:8px 20px;border-radius:20px;display:none;z-index:100}',
    '@media(max-width:600px){#grid{grid-template-columns:1fr}}</style></head>',
    '<body><div style="width:100%;max-width:800px"><div class="container"><h1 id="t">🛡️ Bulk Authenticator</h1>',
    '<div id="input-area"><textarea id="i"></textarea><br><button onclick="load()" id="b">Generate</button></div>',
    '<div id="grid"></div></div><a href="/" class="back-link" id="bk"></a></div><div id="ts" class="toast"></div>',
    '<script>',
    'const lang=navigator.language.startsWith("zh")?"zh":"en";',
    'const i18n={zh:{t:"🛡️ 批量验证器",b:"开始生成",bk:"← 返回单账号模式",s:"已复制",p:"粘贴清单 (账号 密钥)..."},en:{t:"🛡️ Bulk Authenticator",b:"Generate",bk:"← Single Mode",s:"Copied",p:"Paste: Acc Secret..."}};',
    'const D=id=>document.getElementById(id);',
    'D("t").innerText=i18n[lang].t;D("b").innerText=i18n[lang].b;D("bk").innerText=i18n[lang].bk;D("i").placeholder=i18n[lang].p;',
    'let acts=[];',
    'function load(){const lines=D("i").value.trim().split("\\n");acts=[];for(let l of lines){let p=l.trim().split(/\\s+|\\t/).filter(x=>x);if(p.length<2)continue;try{',
    'const n=p[0];const s=p[p.length-1].toUpperCase().replace(/\\s+/g,"");',
    'const totp=new OTPAuth.TOTP({secret:OTPAuth.Secret.fromBase32(s)});',
    'acts.push({n:n,t:totp})}catch(e){}}if(acts.length>0){upd();D("input-area").style.display="none"}}',
    'function upd(){const g=D("grid");const r=30-(Math.floor(Date.now()/1000)%30);g.innerHTML="";for(let a of acts){',
    'const c=a.t.generate();const div=document.createElement("div");div.className="card";',
    'div.innerHTML=`<div class="info"><div class="acc" title="\${a.n}">\${a.n}</div><div class="timer-mini">\${r}s remaining</div></div><div class="otp-val" onclick="cp(\'\${c}\')">\${c}</div>`;',
    'g.appendChild(div)}if(r===30)setTimeout(upd,500)}',
    'function cp(t){navigator.clipboard.writeText(t).then(()=>{const s=D("ts");s.innerText=i18n[lang].s+": "+t;s.style.display="block";setTimeout(()=>s.style.display="none",2000)})}',
    'setInterval(()=>{if(acts.length>0)upd()},1000);',
    '</script></body></html>'
  ];
  return new Response(chunks.join(''), { headers: { "Content-Type": "text/html;charset=UTF-8" } });
}
